/**
 * generate-env.mjs
 *
 * Reads .env.local (dev) or process.env (CI / Cloudflare Pages) and writes:
 *   src/environments/environment.ts        ← dev build
 *   src/environments/environment.prod.ts   ← production build
 *
 * Usage:
 *   node scripts/generate-env.mjs          (reads .env.local if present)
 *
 * In Cloudflare Pages / GitHub Actions, set the env vars in the dashboard
 * and this script will pick them up from process.env automatically.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');

// ── Load .env.local if present (local dev only, gitignored) ─────────────────
const envLocalPath = path.join(root, '.env.local');
if (fs.existsSync(envLocalPath)) {
  const lines = fs.readFileSync(envLocalPath, 'utf-8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim();
    // Only set if not already set by real environment
    if (!process.env[key]) process.env[key] = val;
  }
  console.log('✓  Loaded .env.local');
}

// ── Read values (fall back to safe placeholder if missing) ───────────────────
// Debug: print which expected keys are present (values hidden for security)
const expectedKeys = ['SANITY_PROJECT_ID','SANITY_DATASET','SANITY_READ_TOKEN','SANITY_WRITE_TOKEN','WHATSAPP_PHONE','STORE_NAME','STORE_TAGLINE','ADMIN_PASSWORD','NODE_VERSION'];
console.log('ENV CHECK:', expectedKeys.map(k => `${k}=${process.env[k] ? '✓' : '✗'}`).join(' '));

const required = ['SANITY_PROJECT_ID', 'SANITY_WRITE_TOKEN'];
const missing = required.filter((k) => !process.env[k] || process.env[k].startsWith('YOUR_'));
if (missing.length) {
  console.warn('⚠️   Missing env vars:', missing.join(', '));
  console.warn('    Copy .env.local.example → .env.local and fill in the values.');
}

const cfg = {
  sanityProjectId:  process.env['SANITY_PROJECT_ID']  || 'YOUR_PROJECT_ID',
  sanityDataset:    process.env['SANITY_DATASET']     || 'production',
  sanityApiVersion: '2024-01-01',
  // Use a dedicated read-only token for the browser if provided, otherwise
  // fall back to the write token (less secure but works for single-token setups).
  sanityToken:      process.env['SANITY_READ_TOKEN']  ||
                    process.env['SANITY_WRITE_TOKEN']  || '',
  sanityWriteToken: process.env['SANITY_WRITE_TOKEN'] || '',
  whatsappPhone:    process.env['WHATSAPP_PHONE']     || '919876543210',
  storeName:        process.env['STORE_NAME']         || 'Luxe Storefront',
  storeTagline:     process.env['STORE_TAGLINE']      || 'Curated Fashion & Accessories',
  adminPassword:    process.env['ADMIN_PASSWORD']     || 'admin@luxe2026',
};

// ── Template helper ──────────────────────────────────────────────────────────
function makeEnvFile(production) {
  return `// ⚠️  AUTO-GENERATED by scripts/generate-env.mjs — DO NOT EDIT DIRECTLY
// Run \`npm run generate-env\` to regenerate from .env.local (or CI env vars).
export const environment = {
  production: ${production},
  sanityProjectId:  '${cfg.sanityProjectId}',
  sanityDataset:    '${cfg.sanityDataset}',
  sanityApiVersion: '${cfg.sanityApiVersion}',
  // Read-only token used by the public storefront (Viewer role)
  sanityToken:      '${cfg.sanityToken}',
  // Editor token used by the admin panel (Editor role)
  // ⚠️  This is in the browser bundle. For full security, proxy admin writes
  //     through a Cloudflare Pages Function so this token stays server-side.
  sanityWriteToken: '${cfg.sanityWriteToken}',
  whatsappPhone:    '${cfg.whatsappPhone}',
  storeName:        '${cfg.storeName}',
  storeTagline:     '${cfg.storeTagline}',
  adminPassword:    '${cfg.adminPassword}',
};
`;
}

// ── Write files ───────────────────────────────────────────────────────────────
const envDir = path.join(root, 'src', 'environments');

// Create the directory if it doesn't exist (e.g. on a fresh CI clone)
if (!fs.existsSync(envDir)) {
  fs.mkdirSync(envDir, { recursive: true });
  console.log('✓  Created src/environments/');
}

fs.writeFileSync(path.join(envDir, 'environment.ts'), makeEnvFile(false));
console.log('✓  Wrote src/environments/environment.ts');

fs.writeFileSync(path.join(envDir, 'environment.prod.ts'), makeEnvFile(true));
console.log('✓  Wrote src/environments/environment.prod.ts');

console.log('\nDone. These files are gitignored when they contain real tokens.');
console.log('Commit only the placeholder versions.');
